version: '3.6'

services:

  postgres:
    build: postgres
    restart: always

  redis:
    build: redis
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile-prod
    depends_on:
      - postgres
      - redis
    environment:
      - MK_DEBUG=False
      - MK_SECRET=${SECRET}
    restart: always

  web:
    build:
      context: .
      dockerfile: web/Dockerfile-prod
    depends_on:
      - backend
    ports:
      - ${PORT:-80}:80
    restart: always
