version: '3.6'

services:

  postgres:
    build: postgres

  redis:
    build: redis

  backend:
    build: backend
    volumes:
      - ./backend:/app/src
    depends_on:
      - postgres
      - redis

  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  web:
    build: web
    depends_on:
      - backend
      - frontend
    ports:
      - ${PORT:-8080}:80
